name: ChatColorHandlerTest
version: '${version}'
main: me.dave.chatcolorhandlertest.ChatColorHandlerTest
api-version: '1.20'
softdepend:
  - PlaceholderAPI
  - MiniPlaceholders
commands:
  chatcolorhandlertest:
    description: ChatColorHandlerTest Command
    usage: /chatcolorhandlertest